<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE futbol[
<!ELEMENT futbol (partido+)>
<!ELEMENT partido (local,visitante)>
<!ELEMENT local (#PCDATA)>
<!ELEMENT visitante (#PCDATA)>
  <!ATTLIST local goles CDATA #REQUIRED>
  <!ATTLIST visitante goles CDATA #REQUIRED>
]>

<futbol>
  <partido>
    <local goles="0">Notingham Presa</local>
    <visitante goles="1">Inter Mitente</visitante>
  </partido>
  <partido>
    <local goles="3">Vodka Juniors</local>
    <visitante goles="2">Sparta da Risa</visitante>
  </partido>
  <partido>
    <local goles="4">Water de Munich</local>
    <visitante goles="1"> Esteaua es del grifo</visitante>
  </partido>
</futbol>